
export const subjectResourceLinks: Record<string, string> = {
    'PH101': 'https://drive.google.com/drive/folders/147YmLk5qp1NVxEx8eNDXF9sF_VZxk6GL',
    'MA101': 'https://drive.google.com/drive/folders/1HnAqiAJY6fAuERZkl32TQxqweG8_GkGa',
    'ME101': 'https://drive.google.com/drive/folders/1cyXrwYZiomyyNp2EXWtLp-JXxnn1o2TR',
    'EE101': 'https://drive.google.com/drive/folders/1AqbzsAIEyizz4DBLEDdVfoZ0jMAdQ-OU',
    'HS101': 'https://drive.google.com/drive/folders/14GNnV6koq-Q4SVJMBTzd9cuuACB57y3D',
    'CH101': 'https://drive.google.com/drive/folders/1YZUeyo8h5ozlicDmt3T5au98y2PwH7WP',
    'MA102': 'https://drive.google.com/drive/folders/18DM3oy-T_XYt2SYwkmjiextB8qi6c5bK',
    'CS101': 'https://drive.google.com/drive/folders/1YIXxJA2ztKMYkma5m-mwy1GDYS3NJ2Z9',
    'EC101': 'https://drive.google.com/drive/folders/1vjj1Qk7CmZGK1JcdOiMOh-IW9MFsUnF3',
    'CE102': 'https://drive.google.com/drive/folders/1_X2q2Pri3t3q_zJB8z2M385EXihQ-Ql3',
    'CH111': 'https://drive.google.com/drive/folders/1mwEHInY0pIZoE5QxlhLMjQ9QOgCNW8l4',
    'EC111': 'https://drive.google.com/drive/folders/1cGV6IMWHsQhNI2faj8e6aXnqJ-ZBn-QX',
    'ME111': 'https://drive.google.com/drive/folders/1vMwe3yT07Vukina8UAoWNZWZg47qhF5U',
    'CE101': 'https://drive.google.com/drive/folders/10uqjaCfgaaVaUIKpe9ijcrncxs8LgLAE',
    'PH111': 'https://drive.google.com/drive/folders/1_lqVeLaTOXgwlP9qeYe0l3gJiS69ULbP',
    'EE111': 'https://drive.google.com/drive/folders/1EmNHA8AmoEe3D58oa18kOFWsVKrL49Wu',
    'MA201': 'https://drive.google.com/drive/folders/1hJzYAOCfDoGsvSl-Ezik9rLNZxUY8Wol',
    'EC202': 'https://drive.google.com/drive/folders/1RN9YAMeqFfy_JigPpFq0ySaucnI6osXU',
    'EI203': 'https://drive.google.com/drive/folders/1Qr226q5c6JCjuVckmEbqGYWqiNzbONzS',
    'CS222': 'https://drive.google.com/drive/folders/14kfE9Rjc_jA_bKyzsolXNydL2-38nst9',
    'EI201': 'https://drive.google.com/drive/folders/1DM_ahTIYS9AX5_hUJijMxyHDLD4lJOcG',
    'CS213': 'https://drive.google.com/drive/folders/16waHTR9WE8LFn5Zfs2fW2-06aCsLbVh5',
};

const DEFAULT_RESOURCE_LINK = "https://sites.google.com/view/infinitsilchar/home";

const addDefaultResourceLinks = (subjects: any[]) => {
    return subjects.map(subject => {
        if (!subject.resourceUrl || subject.resourceUrl === '#') {
            const link = subjectResourceLinks[subject.code] || DEFAULT_RESOURCE_LINK;
            return { ...subject, resourceUrl: link };
        }
        return subject;
    });
};
  

export const branchCodeMapping = {
    '1': 'CE',
    '2': 'CSE',
    '3': 'EE',
    '4': 'ECE',
    '5': 'EIE',
    '6': 'ME',
};
  

const rawCourseData: Record<string, any> = {
    '1': { // Civil Engineering
      '1': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'CE101', name: 'Engineering Graphics & Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '2': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '3': [
        { code: 'CE201', name: 'Mechanics of Materials', credits: 4 },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
        { code: 'CE202', name: 'Civil Engineering Material, Testing and Evaluation', credits: 3 },
        { code: 'CE203', name: 'Introduction to Geo Sciences', credits: 3 },
        { code: 'CE204', name: 'Surveying & Geomatics', credits: 4 },
        { code: 'CE205', name: 'Fluid Mechanics', credits: 3 },
        { code: 'CE211', name: 'Surveying & Geomatics Laboratory', credits: 2 },
        { code: 'CE212', name: 'Civil Engineering Materials, Testing and Evaluation Laboratory', credits: 2 },
        { code: 'CE213', name: 'Civil Engineering Drawing Laboratory', credits: 2 },
      ],
      '4': [
        { code: 'CE206', name: 'Structural Analysis - I', credits: 4 },
        { code: 'CE207', name: 'Hydraulics', credits: 4 },
        { code: 'CE208', name: 'Design of Concrete Structures-I', credits: 4 },
        { code: 'CE209', name: 'Transportation Engineering', credits: 4 },
        { code: 'CE210', name: 'Geotechnical Engineering', credits: 4 },
        { code: 'CE214', name: 'Hydraulics Laboratory', credits: 2 },
        { code: 'CE215', name: 'Concrete Laboratory', credits: 2 },
        { code: 'CE216', name: 'Geotechnical Engineering Laboratory', credits: 2 },
        { code: 'CE217', name: 'Geo Science Laboratory', credits: 2 },
      ],
      '5': [
        { code: 'CE301', name: 'Design of Concrete Structures - II', credits: 4 },
        { code: 'CE302', name: 'Foundation Engineering', credits: 4 },
        { code: 'CE303', name: 'Structural Analysis-II', credits: 4 },
        { code: 'CE304', name: 'Surface and Ground water Hydrology', credits: 4 },
        { code: 'CE305', name: 'Water Supply Engineering', credits: 4 },
        { code: 'CE311', name: 'Detailing of Civil Engineering Structures', credits: 2 },
        { code: 'CE312', name: 'Foundation Engineering Laboratory', credits: 2 },
        { code: 'CE313', name: 'Transportation Engineering Laboratory', credits: 2 },
        { code: 'CE314', name: 'Water Resources Engineering Laboratory', credits: 2 },
      ],
      '6': [
        { code: 'CE306', name: 'Civil Engineering Estimation', credits: 3 },
        { code: 'CE307', name: 'Design of Steel Structures', credits: 4 },
        { code: 'CE308', name: 'Sewage Treatment And Disposal', credits: 3 },
        { code: 'CE309', name: 'Structural Analysis- III', credits: 4 },
        { code: 'CE331', name: 'Soil Dynamics and Machine Foundation (Elec. I)', credits: 4 },
        { code: 'CE332', name: 'Water Resource & Irrigation Engineering (Elec. I)', credits: 4 },
        { code: 'CE333', name: 'Elements of Ocean Engineering (Elec. I)', credits: 4 },
        { code: 'CE334', name: 'Railway and Bridge Engineering (Elec. I)', credits: 4 },
        { code: 'CE381', name: 'Modeling, Simulation and Application (Open Elec. I)', credits: 4 },
        { code: 'CE382', name: 'Remote Sensing and GIS (Open Elec. I)', credits: 4 },
        { code: 'CE315', name: 'Environment Engineering Laboratory', credits: 2 },
        { code: 'CE316', name: 'Computer Aided Design Laboratory', credits: 2 },
        { code: 'CE317', name: 'Structural Engineering Laboratory', credits: 2 },
      ],
      '7': [
        { code: 'HSXXX_Econ_CE', name: 'Engineering Economics/Management Studies', credits: 3 },
        { code: 'CE401', name: 'Concrete Technology', credits: 3 },
        { code: 'CE431', name: 'Coastal Engineering (Elec. II)', credits: 4 },
        { code: 'CE432', name: 'Advanced Structural Analysis (Elec. II)', credits: 4 },
        { code: 'CE433', name: 'Advanced Foundation Engineering (Elec. II)', credits: 4 },
        { code: 'CE434', name: 'Dynamics of Structures (Elec. II)', credits: 4 },
        { code: 'CE435', name: 'Open Channel Flow (Elec. II)', credits: 4 },
        { code: 'CE481', name: 'Data Analytics in Engineering (Open Elec. II)', credits: 3 },
        { code: 'CE482', name: 'Numerical Methods in Engineering (Open Elec. II)', credits: 3 },
        { code: 'CE498', name: 'Project I', credits: 4 },
        { code: 'CE430', name: 'Industrial Training', credits: 2 },
      ],
      '8': [
        { code: 'HSXXX_Mgmt_CE', name: 'Engineering Economics / Management', credits: 3 },
        { code: 'CE451', name: 'Earthquake Resistant Design of Structures (Elec. III)', credits: 3 },
        { code: 'CE452', name: 'Elementary Performance-Based Seismic Design (Elec. III)', credits: 3 },
        { code: 'CE453', name: 'Hydraulic Structures (Elec. III)', credits: 3 },
        { code: 'CE454', name: 'Application of Geosynthetics (Elec. III)', credits: 3 },
        { code: 'CE455', name: 'Construction Engineering & Management (Elec. III)', credits: 3 },
        { code: 'CE491', name: 'Finite Elements Methods in Engineering (Open Elec. III)', credits: 3 },
        { code: 'CE492', name: 'Optimization Techniques (Open Elec. III)', credits: 3 },
        { code: 'CE493', name: 'Engineering Risk Analysis (Open Elec. III)', credits: 3 },
        { code: 'CE499', name: 'Project II', credits: 6 },
      ],
    },
    '2': { // Computer Science and Engineering
      '1': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '2': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'CE101', name: 'Engineering Graphics & Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '3': [
        { code: 'CS201', name: 'Data Structure', credits: 4 },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
        { code: 'CS202', name: 'Discrete Structures', credits: 4 },
        { code: 'EC221', name: 'Circuits and Switching', credits: 4 },
        { code: 'EE223', name: 'Microprocessor', credits: 4 },
        { code: 'CS213', name: 'Data Structure Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CS213'] },
        { code: 'EE214', name: 'Microprocessor Laboratory', credits: 2 },
        { code: 'EC212', name: 'Circuits and Switching Laboratory', credits: 2 },
      ],
      '4': [
        { code: 'CS204', name: 'Theory of Computation', credits: 4 },
        { code: 'CS205', name: 'Computer Architecture and Organization', credits: 4 },
        { code: 'CS206', name: 'Algorithms', credits: 4 },
        { code: 'MA221', name: 'Mathematics-IV (Introduction to Stochastic Processes)', credits: 4 },
        { code: 'CS207', name: 'Signals & Data Communication', credits: 4 },
        { code: 'CS218', name: 'Object Oriented Programming Laboratory', credits: 3 },
        { code: 'CS219', name: 'Algorithms Laboratory', credits: 2 },
        { code: 'CS210', name: 'Signals & Data Communication Laboratory', credits: 2 },
        { code: 'CS211', name: 'Applied Probability Laboratory', credits: 2 },
      ],
      '5': [
        { code: 'CS301', name: 'Computer Network', credits: 4 },
        { code: 'CS302', name: 'Database Management Systems', credits: 4 },
        { code: 'CS303', name: 'Operating System', credits: 4 },
        { code: 'CS304', name: 'Software Engineering', credits: 4 },
        { code: 'CS305', name: 'Graph Theory', credits: 4 },
        { code: 'CS311', name: 'Computer Network Laboratory', credits: 2 },
        { code: 'CS312', name: 'Database Laboratory', credits: 2 },
        { code: 'CS313', name: 'Operating System Laboratory', credits: 2 },
        { code: 'CS314', name: 'Software Engineering Laboratory', credits: 2 },
      ],
      '6': [
        { code: 'CS306', name: 'Principles of Programming Language', credits: 4 },
        { code: 'CS307', name: 'Compiler Design', credits: 4 },
        { code: 'CS308', name: 'Graphics & Multimedia', credits: 4 },
        { code: 'CS331', name: 'Social Network Analysis (Elec. I)', credits: 4 },
        { code: 'CS332', name: 'Natural Language Processing (Elec. I)', credits: 4 },
        { code: 'CS333', name: 'Digital Image Processing (Elec. I)', credits: 4 },
        { code: 'CS334', name: 'Speech Processing (Elec. I)', credits: 4 },
        { code: 'CS335', name: 'Artificial Neural Network (Elec. I)', credits: 4 },
        { code: 'CS336', name: 'Linux Operating System (Elec. I)', credits: 4 },
        { code: 'CS381', name: 'Simulation and Modeling (Open Elec. I)', credits: 4 },
        { code: 'CS382', name: 'Introduction to Blockchain (Open Elec. I)', credits: 4 },
        { code: 'CS315', name: 'Object Oriented Design Laboratory', credits: 2 },
        { code: 'CS316', name: 'Compiler Laboratory', credits: 2 },
        { code: 'CS317', name: 'Graphics & Multimedia Laboratory', credits: 2 },
        { code: 'CS321', name: 'Social Network Analysis Laboratory (Elec. I Lab)', credits: 2 },
        { code: 'CS322', name: 'Natural Language Processing Laboratory (Elec. I Lab)', credits: 2 },
        { code: 'CS323', name: 'Digital Image Processing Laboratory (Elec. I Lab)', credits: 2 },
        { code: 'CS324', name: 'Speech Processing Laboratory (Elec. I Lab)', credits: 2 },
        { code: 'CS325', name: 'Artificial Neural Network Laboratory (Elec. I Lab)', credits: 2 },
        { code: 'CS326', name: 'Linux Operating System Laboratory (Elec. I Lab)', credits: 2 },
      ],
      '7': [
        { code: 'CS401', name: 'Artificial Intelligence', credits: 4 },
        { code: 'CS431', name: 'Machine Learning (Elec. II)', credits: 3 },
        { code: 'CS432', name: 'Pattern Recognition (Elec. II)', credits: 3 },
        { code: 'CS433', name: 'Computational Geometry (Elec. II)', credits: 3 },
        { code: 'CS434', name: 'Cryptography and Security (Elec. II)', credits: 3 },
        { code: 'CS435', name: 'Wireless Network (Elec. II)', credits: 3 },
        { code: 'CS436', name: 'VLSI Physical Design (Elec. II)', credits: 3 },
        { code: 'CS437', name: 'Distributed System (Elec. II)', credits: 3 },
        { code: 'CS438', name: 'Internet of Things (Elec. II)', credits: 3 },
        { code: 'CS439', name: 'Data Mining (Elec. II)', credits: 3 },
        { code: 'CS481', name: 'Web Technology (Open Elec. II)', credits: 3 },
        { code: 'CS482', name: 'Introduction to GPU Computing (Open Elec. II)', credits: 3 },
        { code: 'HS402_BM_CS', name: 'Business Management', credits: 3 },
        { code: 'CS497', name: 'Industrial Training (Minimum 6 weeks)', credits: 2 },
        { code: 'CS498', name: 'Project-I', credits: 4 },
      ],
      '8': [
        { code: 'HS401_ME_CS', name: 'Managerial Economics', credits: 3 },
        { code: 'CS440', name: 'Quantum Computing (Elec. III)', credits: 4 },
        { code: 'CS441', name: 'Text Mining and Analytics (Elec. III)', credits: 4 },
        { code: 'CS442', name: 'Wireless Sensor Network (Elec. III)', credits: 4 },
        { code: 'CS443', name: 'Applied Parallel Programming (Elec. III)', credits: 4 },
        { code: 'CS444', name: 'Information Theory and Coding (Elec. III)', credits: 4 },
        { code: 'CS445', name: 'Big Data Analysis (Elec. III)', credits: 4 },
        { code: 'CS483', name: 'Time Series Analysis (Open Elec. III)', credits: 3 },
        { code: 'CS484', name: 'Cloud Computing (Open Elec. III)', credits: 3 },
        { code: 'CS485', name: 'Machine Translation (Open Elec. III)', credits: 3 },
        { code: 'CS499', name: 'Project II', credits: 6 },
      ],
    },
    '3': { // Electrical Engineering
      '1': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'CE101', name: 'Engineering Graphics & Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Academic Activities', credits: 0 },
      ],
      '2': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Academic Activities', credits: 0 },
      ],
      '3': [
        { code: 'EE201', name: 'Signals and Systems', credits: 4 },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
        { code: 'EE202', name: 'Analog Electronics', credits: 4 },
        { code: 'EE203', name: 'Energy Science and Technology', credits: 3 },
        { code: 'EE204', name: 'Measuring Instruments and Measurements', credits: 4 },
        { code: 'EE205', name: 'Electromagnetic Field Theory', credits: 4 },
        { code: 'EE211', name: 'Programming and Simulation Laboratory', credits: 2 },
        { code: 'EE212', name: 'Measurement Laboratory', credits: 2 },
        { code: 'EC216', name: 'Analog Electronics Laboratory', credits: 2 },
      ],
      '4': [
        { code: 'EE206', name: 'Electrical Machines - I', credits: 4 },
        { code: 'EE207', name: 'Power Systems I', credits: 4 },
        { code: 'EE208', name: 'Digital Electronics', credits: 4 },
        { code: 'EE209', name: 'Circuit Theory', credits: 4 },
        { code: 'EE210', name: 'Microprocessors & Microcontrollers', credits: 3 },
        { code: 'CS221', name: 'Programming & Data Structure', credits: 3 },
        { code: 'EE213', name: 'Circuit Theory Laboratory', credits: 2 },
        { code: 'EE214', name: 'Microprocessor & Microcontroller Laboratory', credits: 2 },
        { code: 'EE215', name: 'Digital Electronics Laboratory', credits: 2 },
      ],
      '5': [
        { code: 'EE301', name: 'Control Systems', credits: 4 },
        { code: 'EE302', name: 'Power Systems II', credits: 4 },
        { code: 'EE303', name: 'Electrical Machines II', credits: 4 },
        { code: 'EE304', name: 'Power Electronics', credits: 4 },
        { code: 'EE305', name: 'Digital Signal Processing', credits: 3 },
        { code: 'EE311', name: 'Electrical Machine Laboratory-I', credits: 2 },
        { code: 'EE312', name: 'Power System Laboratory-I', credits: 2 },
        { code: 'EE313', name: 'Control System Laboratory', credits: 2 },
        { code: 'EE314', name: 'Signal Processing Laboratory', credits: 2 },
      ],
      '6': [
        { code: 'EE306', name: 'Switchgear and Protection', credits: 4 },
        { code: 'EE307', name: 'Industrial Drives', credits: 4 },
        { code: 'EC327', name: 'Analog and Digital Communication', credits: 3 },
        { code: 'EE308', name: 'Modern Control Systems', credits: 4 },
        { code: 'EE331', name: 'Digital Control Systems (Elec. I)', credits: 3 },
        { code: 'EE332', name: 'Advanced Power Electronics and Devices (Elec. I)', credits: 3 },
        { code: 'EE333', name: 'Computer Organization (Elec. I)', credits: 3 },
        { code: 'EE334', name: 'LT & HT Distribution Systems (Elec. I)', credits: 3 },
        { code: 'EE335', name: 'Introduction to VLSI (Elec. I)', credits: 3 },
        { code: 'EE336', name: 'Renewable Energy (Elec. I)', credits: 3 },
        { code: 'EE381', name: 'Optimization Methods and its Application in Engineering (Open Elec. I)', credits: 3 },
        { code: 'EE382', name: 'Fuzzy Set Theory and Applications (Open Elec. I)', credits: 3 },
        { code: 'EE383', name: 'Adaptive Signal Processing (Open Elec. I)', credits: 3 },
        { code: 'EE384', name: 'Mathematical Methods in Dynamic Systems (Open Elec. I)', credits: 3 },
        { code: 'EE385', name: 'Software-based System Design (Open Elec. I)', credits: 3 },
        { code: 'EE386', name: 'Hardware-based System Design (Open Elec. I)', credits: 3 },
        { code: 'EE315', name: 'Electrical Machine Laboratory II', credits: 2 },
        { code: 'EE316', name: 'Power System Laboratory II', credits: 2 },
        { code: 'EE317', name: 'Power Electronics and Drives Laboratory', credits: 2 },
      ],
      '7': [
        { code: 'EE401', name: 'Instrumentation', credits: 4 },
        { code: 'MS401_Biz_EE', name: 'Business Management', credits: 3 },
        { code: 'EE431', name: 'Switch Mode Power Supply (Elec. II)', credits: 3 },
        { code: 'EE432', name: 'Electric Power Utilization and Traction (Elec. II)', credits: 3 },
        { code: 'EE433', name: 'Biomedical Signal Processing and Control (Elec. II)', credits: 3 },
        { code: 'EE434', name: 'Electric Power Quality (Elec. II)', credits: 3 },
        { code: 'EE435', name: 'Optimal Control (Elec. II)', credits: 3 },
        { code: 'EE436', name: 'Modelling and Control of AC Drives (Elec. II)', credits: 3 },
        { code: 'EE437', name: 'Computer Applications in Power Systems (Elec. II)', credits: 3 },
        { code: 'EE438', name: 'Power System Operation and Control (Elec. II)', credits: 3 },
        { code: 'EE439', name: 'Data Acquisition and Signal Conditioning (Elec. II)', credits: 3 },
        { code: 'EE440', name: 'AC-DC Microgrid (Elec. II)', credits: 3 },
        { code: 'EE441', name: 'Flexible AC Transmission Systems (Elec. II)', credits: 3 },
        { code: 'EE442', name: 'High Voltage AC/DC (Elec. II)', credits: 3 },
        { code: 'EE443', name: 'Intelligent and Knowledge Based Systems (Elec. II)', credits: 3 },
        { code: 'EE444', name: 'Demand Side Management (Elec. II)', credits: 3 },
        { code: 'EE445', name: 'Control of Wind Energy Conversion System and its Challenges (Elec. II)', credits: 3 },
        { code: 'EE446', name: 'Geometrical Aspect of Control Systems (Elec. II)', credits: 3 },
        { code: 'EE447', name: 'Nonlinear Systems (Elec. II)', credits: 3 },
        { code: 'EE448', name: 'VLSI System Design (Elec. II)', credits: 3 },
        { code: 'EE481', name: 'Introduction to Biomedical Engineering (Open Elec. II)', credits: 3 },
        { code: 'EE482', name: 'Optimization Techniques and Numerical Methods (Open Elec. II)', credits: 3 },
        { code: 'EE483', name: 'Industrial Instrumentation (Open Elec. II)', credits: 3 },
        { code: 'EE484', name: 'Artificial Neural Networks (Open Elec. II)', credits: 3 },
        { code: 'EE485', name: 'Design Aspect of Control Systems (Open Elec. II)', credits: 3 },
        { code: 'EE486', name: 'Modelling and Simulation of Dynamical Systems (Open Elec. II)', credits: 3 },
        { code: 'EE497', name: 'Industrial Training (Minimum 6 weeks)', credits: 2 },
        { code: 'EE498', name: 'Project I', credits: 4 },
      ],
      '8': [
        { code: 'EE451', name: 'Power System Reliability and Deregulation (Elec. III)', credits: 3 },
        { code: 'EE452', name: 'Power System Stability and Control (Elec. III)', credits: 3 },
        { code: 'EE453', name: 'Electrical Networks and Pricing (Elec. III)', credits: 3 },
        { code: 'EE454', name: 'System Identification and Parameter Estimation (Elec. III)', credits: 3 },
        { code: 'EE455', name: 'Advanced Control Systems (Elec. III)', credits: 3 },
        { code: 'EE456', name: 'Advanced Digital Signal Processing (Elec. III)', credits: 3 },
        { code: 'EE457', name: 'Biomedical Instrumentation (Elec. III)', credits: 3 },
        { code: 'EE458', name: 'CAD for VLSI Systems (Elec. III)', credits: 3 },
        { code: 'EE459', name: 'EHV Transmission (Elec. III)', credits: 3 },
        { code: 'EE460', name: 'Power Electronics Application to Wind and Solar Energy System (Elec. III)', credits: 3 },
        { code: 'EE466', name: 'Distribution Systems Planning and Automation (Elec. III)', credits: 3 },
        { code: 'EE467', name: 'Intelligent Algorithms for Power Systems (Elec. III)', credits: 3 },
        { code: 'EE468', name: 'Hydro-electric Engineering (Elec. III)', credits: 3 },
        { code: 'EE469', name: 'Non-Conventional and Distributed Generation (Elec. III)', credits: 3 },
        { code: 'EE470', name: 'Navigation, Guidance and Control (Elec. III)', credits: 3 },
        { code: 'EE471', name: 'Non-linear System Analysis and Control (Elec. III)', credits: 3 },
        { code: 'EE472', name: 'Computer Relaying and Phasor Measurement Unit (Elec. III)', credits: 3 },
        { code: 'EE473', name: 'Smart Grid Technologies (Elec. III)', credits: 3 },
        { code: 'EE474', name: 'Advanced Instrumentation (Elec. III)', credits: 3 },
        { code: 'EE475', name: 'Special Electrical Machines and Drives (Elec. III)', credits: 3 },
        { code: 'EE476', name: 'Intelligent Control (Elec. III)', credits: 3 },
        { code: 'EE477', name: 'Energy Auditing, Conservation and Management (Elec. III)', credits: 3 },
        { code: 'HS401_Econ_EE', name: 'Managerial Economics', credits: 3 },
        { code: 'EE491', name: 'Electric Vehicles (Open Elec. III)', credits: 3 },
        { code: 'EE492', name: 'Soft Computing Techniques and Applications (Open Elec. III)', credits: 3 },
        { code: 'EE493', name: 'Electrical Safety (Open Elec. III)', credits: 3 },
        { code: 'EE494', name: 'Control System Components (Open Elec. III)', credits: 3 },
        { code: 'EE499', name: 'Project II', credits: 6 },
      ],
    },
    '4': { // Electronics and Communication Engineering
      '1': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'CE101', name: 'Engineering Graphics & Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '2': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '3': [
        { code: 'CS222', name: 'Data Structure & Algorithm', credits: 4, resourceUrl: subjectResourceLinks['CS222'] },
        { code: 'CS213', name: 'Data Structure and Algorithm Lab', credits: 2, resourceUrl: subjectResourceLinks['CS213'] },
        { code: 'EC201', name: 'Network Theory', credits: 3 },
        { code: 'EC202', name: 'Analog Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC202'] },
        { code: 'EC203', name: 'Signals & Systems', credits: 4 },
        { code: 'EC211', name: 'Analog Electronics Laboratory', credits: 2 },
        { code: 'EE221', name: 'Electrical Machines', credits: 4 },
        { code: 'EE212', name: 'Electrical Machines Laboratory', credits: 2 },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
      ],
      '4': [], '5': [], '6': [], '7': [], '8': [],
    },
    '5': { // Electronics and Instrumentation Engineering
      '1': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'CE101', name: 'Engineering Graphics Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Academic Activities', credits: 0 },
      ],
      '2': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Academic Activities', credits: 0 },
      ],
      '3': [
        { code: 'EI201', name: 'Electrical & Electronic Measurements', credits: 4, resourceUrl: subjectResourceLinks['EI201'] },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
        { code: 'EI202', name: 'Analog Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC202'] },
        { code: 'EI203', name: 'Circuits & Networks', credits: 4, resourceUrl: subjectResourceLinks['EI203'] },
        { code: 'CS222', name: 'Data Structure & Algorithm', credits: 4, resourceUrl: subjectResourceLinks['CS222'] },
        { code: 'EI211', name: 'Measurement Lab', credits: 2 },
        { code: 'EI212', name: 'Analog Electronics Lab', credits: 2 },
        { code: 'EI213', name: 'Circuits & Networks Lab', credits: 2 },
        { code: 'CS223', name: 'Data Structure and Algorithm Lab', credits: 2, resourceUrl: subjectResourceLinks['CS213'] },
      ],
      '4': [
        { code: 'EI204', name: 'Sensors and Transducers', credits: 4 },
        { code: 'EI205', name: 'Signals and Systems', credits: 4 },
        { code: 'EI206', name: 'Control System-I', credits: 4 },
        { code: 'EI207', name: 'Digital Electronics', credits: 4 },
        { code: 'EI208', name: 'Power Electronics & Drives', credits: 3 },
        { code: 'EI214', name: 'Sensor and Transducers Lab', credits: 2 },
        { code: 'EI215', name: 'Control System Lab', credits: 2 },
        { code: 'EI216', name: 'Digital Electronics Lab', credits: 2 },
        { code: 'EI217', name: 'Power Electronics Lab', credits: 2 },
      ],
      '5': [
        { code: 'EI301', name: 'Industrial Instrumentation-I', credits: 4 },
        { code: 'EI302', name: 'Microprocessors & Micro Controllers', credits: 4 },
        { code: 'EI303', name: 'Biomedical Instrumentation', credits: 3 },
        { code: 'EI304', name: 'Control System-II', credits: 4 },
        { code: 'EI305', name: 'Communication & Telemetry', credits: 4 },
        { code: 'EI311', name: 'Microprocessors & Micro Controllers Lab', credits: 2 },
        { code: 'EI312', name: 'Biomedical Instrumentation Lab', credits: 2 },
        { code: 'EI313', name: 'Communication & Telemetry Lab', credits: 2 },
        { code: 'EI314', name: 'Virtual Instrumentation Lab', credits: 3 },
      ],
      '6': [
        { code: 'EI306', name: 'Industrial Instrumentation-II', credits: 4 },
        { code: 'EI307', name: 'Process Control Engineering', credits: 4 },
        { code: 'EI308', name: 'Digital Signal Processing', credits: 4 },
        { code: 'EI331', name: 'IC and VLSI Design (Elec. I)', credits: 4 },
        { code: 'EI332', name: 'Power Plant Instrumentation (Elec. I)', credits: 4 },
        { code: 'EI381', name: 'Air Pollution and Environmental Instrumentation (Open Elec. I)', credits: 3 },
        { code: 'EI315', name: 'Instrumentation Lab', credits: 2 },
        { code: 'EI316', name: 'Industrial Process Control and Automation Lab', credits: 2 },
        { code: 'EI317', name: 'Digital Signal Processing Lab', credits: 2 },
        { code: 'EI318', name: 'Simulation, Design & Fabrication Lab', credits: 2 },
      ],
      '7': [
        { code: 'EI401', name: 'Analytical & Optical Instrumentation', credits: 3 },
        { code: 'EI431', name: 'Advanced Instrumentation (Elec. II)', credits: 4 },
        { code: 'EI481', name: 'Robotics and Automation (Open Elec. II)', credits: 3 },
        { code: 'HS401', name: 'Managerial Economics', credits: 3 },
        { code: 'EI497', name: 'Industrial Training', credits: 2 },
        { code: 'EI498', name: 'Project I', credits: 4 },
      ],
      '8': [
        { code: 'MS401', name: 'Business Management', credits: 3 },
        { code: 'EI441', name: 'Advanced Sensors and Signal Processing (Elec. III)', credits: 4 },
        { code: 'EI490', name: 'Intelligent Instrumentation (Open Elec. III)', credits: 3 },
        { code: 'EI499', name: 'Project II', credits: 6 },
      ],
    },
    '6': { // Mechanical Engineering
      '1': [
        { code: 'PH101', name: 'Physics', credits: 4, resourceUrl: subjectResourceLinks['PH101'] },
        { code: 'MA101', name: 'Mathematics I', credits: 4, resourceUrl: subjectResourceLinks['MA101'] },
        { code: 'ME101', name: 'Engineering Mechanics', credits: 4, resourceUrl: subjectResourceLinks['ME101'] },
        { code: 'EE101', name: 'Basic Electrical Engineering', credits: 4, resourceUrl: subjectResourceLinks['EE101'] },
        { code: 'HS101', name: 'Communicative English', credits: 3, resourceUrl: subjectResourceLinks['HS101'] },
        { code: 'CE101', name: 'Engineering Graphics & Design', credits: 3, resourceUrl: subjectResourceLinks['CE101'] },
        { code: 'PH111', name: 'Physics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['PH111'] },
        { code: 'EE111', name: 'Basic Electrical Engineering Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EE111'] },
        { code: 'HS111', name: 'Language Laboratory', credits: 2 },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '2': [
        { code: 'CH101', name: 'Chemistry', credits: 4, resourceUrl: subjectResourceLinks['CH101'] },
        { code: 'MA102', name: 'Mathematics II', credits: 4, resourceUrl: subjectResourceLinks['MA102'] },
        { code: 'CS101', name: 'Introduction to Programming', credits: 4, resourceUrl: subjectResourceLinks['CS101'] },
        { code: 'EC101', name: 'Basic Electronics', credits: 4, resourceUrl: subjectResourceLinks['EC101'] },
        { code: 'CE102', name: 'Environmental Science & Engineering', credits: 3, resourceUrl: subjectResourceLinks['CE102'] },
        { code: 'CH111', name: 'Chemistry Laboratory', credits: 2, resourceUrl: subjectResourceLinks['CH111'] },
        { code: 'CS111', name: 'Programming Laboratory', credits: 2 },
        { code: 'EC111', name: 'Basic Electronics Laboratory', credits: 2, resourceUrl: subjectResourceLinks['EC111'] },
        { code: 'ME111', name: 'Workshop Practice', credits: 2, resourceUrl: subjectResourceLinks['ME111'] },
        { code: 'EAA', name: 'Extra-Curricular Activities', credits: 0 },
      ],
      '3': [
        { code: 'ME201', name: 'Engineering Thermodynamics', credits: 4 },
        { code: 'ME202', name: 'Theory of Machines', credits: 4 },
        { code: 'MA201', name: 'Mathematics III', credits: 4, resourceUrl: subjectResourceLinks['MA201'] },
        { code: 'ME203', name: 'Fluid Mechanics', credits: 4 },
        { code: 'ME204', name: 'Manufacturing Process', credits: 3 },
        { code: 'ME205', name: 'Material Science', credits: 3 },
        { code: 'ME211', name: 'Machine Drawing Lab', credits: 2 },
        { code: 'ME212', name: 'Manufacturing Lab', credits: 2 },
        { code: 'ME213', name: 'Thermo-Fluid Lab-I', credits: 2 },
      ],
      '4': [
        { code: 'ME206', name: 'Heat Transfer', credits: 3 },
        { code: 'ME207', name: 'Fluid Dynamics and Hydraulic Machines', credits: 3 },
        { code: 'ME208', name: 'Mechanics of Solids', credits: 3 },
        { code: 'ME209', name: 'Instrumentation and Measurement', credits: 3 },
        { code: 'ME210', name: 'Machining Science', credits: 3 },
        { code: 'ME217', name: 'Energy Science and Technology', credits: 3 },
        { code: 'ME214', name: 'Material Testing Lab', credits: 2 },
        { code: 'ME215', name: 'Instrumentation and Measurement Lab', credits: 2 },
        { code: 'ME216', name: 'Thermo-Fluid Lab - II', credits: 2 },
      ],
      '5': [
        { code: 'ME301', name: 'Heat Transfer', credits: 4 },
        { code: 'ME302', name: 'Machine Design - I', credits: 4 },
        { code: 'ME303', name: 'Turbomachinery', credits: 4 },
        { code: 'ME304', name: 'Advanced Solid Mechanics', credits: 4 },
        { code: 'ME305', name: 'I. C. Engine', credits: 3 },
        { code: 'ME306', name: 'Advanced Manufacturing Process', credits: 3 },
        { code: 'ME311', name: 'Fluid Machinery Lab', credits: 2 },
        { code: 'ME312', name: 'Machining Lab', credits: 2 },
        { code: 'ME313', name: 'Heat Transfer Lab', credits: 2 },
      ],
      '6': [
        { code: 'ME307', name: 'Machine Design - II', credits: 4 },
        { code: 'ME308', name: 'Automobile Engineering', credits: 4 },
        { code: 'ME309', name: 'Power Plant Engineering', credits: 4 },
        { code: 'ME310', name: 'Dynamics and Control of Machinery', credits: 4 },
        { code: 'ME331', name: 'Computer Numerical Control of Machine Tools (Elec. I)', credits: 3 },
        { code: 'ME332', name: 'Diagnostic Maintenance of Mechanical Equipments (Elec. I)', credits: 3 },
        { code: 'ME333', name: 'Plant Layout and Automated Material Handling (Elec. I)', credits: 3 },
        { code: 'ME334', name: 'Ferrous and Nonferrous Material (Elec. I)', credits: 3 },
        { code: 'ME335', name: 'Fuel and Combustion (Elec. I)', credits: 3 },
        { code: 'ME336', name: 'Theory of Elasticity and Plasticity (Elec. I)', credits: 3 },
        { code: 'ME337', name: 'Gas Dynamics (Elec. I)', credits: 3 },
        { code: 'ME338', name: 'Gas Turbine and Jet Propulsion (Elec. I)', credits: 3 },
        { code: 'ME339', name: 'Metal Cutting and Cutting Tool Design (Elec. I)', credits: 3 },
        { code: 'ME381', name: 'Computational Fluid Dynamics (Open Elec. I)', credits: 3 },
        { code: 'ME382', name: 'Finite Element Method (Open Elec. I)', credits: 3 },
        { code: 'ME383', name: 'Reliability Engineering (Open Elec. I)', credits: 3 },
        { code: 'ME384', name: 'Renewable Energy (Open Elec. I)', credits: 3 },
        { code: 'ME385', name: 'Engineering Inspection and Quality Control (Open Elec. I)', credits: 3 },
        { code: 'ME314', name: 'Automobile Lab', credits: 2 },
        { code: 'ME315', name: 'Dynamics Lab', credits: 2 },
        { code: 'ME316', name: 'Machine Design Lab', credits: 2 },
      ],
      '7': [
        { code: 'ME401', name: 'Industrial Engineering and Operations Research', credits: 3 },
        { code: 'ME431', name: 'Advanced Machining Process (Elec. II)', credits: 4 },
        { code: 'ME432', name: 'Convective Heat and Mass Transfer (Elec. II)', credits: 4 },
        { code: 'ME433', name: 'Fundamentals of Industrial Design (Elec. II)', credits: 4 },
        { code: 'ME434', name: 'Viscous Fluid Flow (Elec. II)', credits: 4 },
        { code: 'ME435', name: 'Mechanics of Composite Materials (Elec. II)', credits: 4 },
        { code: 'ME436', name: 'Computer Aided Design (Elec. II)', credits: 4 },
        { code: 'ME437', name: 'Refrigeration (Elec. II)', credits: 4 },
        { code: 'ME481', name: 'Battery and Fuel Cell Technologies (Open Elec. II)', credits: 3 },
        { code: 'ME482', name: 'Mechatronics (Open Elec. II)', credits: 3 },
        { code: 'ME483', name: 'Uncertainty Quantification (Open Elec. II)', credits: 3 },
        { code: 'ME484', name: 'Hydraulic Machines (Open Elec. II)', credits: 3 },
        { code: 'IC401_Ent_ME', name: 'Entrepreneurship and Venture Development (Open Elec. II)', credits: 3 },
        { code: 'HS401_Econ_ME', name: 'Managerial Economics', credits: 3 },
        { code: 'ME497', name: 'Industrial Training (Minimum 6 weeks)', credits: 2 },
        { code: 'ME498', name: 'Project I', credits: 4 },
      ],
      '8': [
        { code: 'HS401_BM_ME', name: 'Business Management', credits: 3 },
        { code: 'ME451', name: 'Computer Integrated Manufacturing (Elec. III)', credits: 3 },
        { code: 'ME452', name: 'Condition Monitoring of Manufacturing Processes (Elec. III)', credits: 3 },
        { code: 'ME453', name: 'Engineering Fracture Mechanics (Elec. III)', credits: 3 },
        { code: 'ME454', name: 'Heat Transfer Application in Biological Systems (Elec. III)', credits: 3 },
        { code: 'ME455', name: 'Mechanical Vibration (Elec. III)', credits: 3 },
        { code: 'ME456', name: 'Two Phase Flow (Elec. III)', credits: 3 },
        { code: 'ME457', name: 'Air Conditioning (Elec. III)', credits: 3 },
        { code: 'ME491', name: 'Interfacial Instability and Applications (Open Elec. III)', credits: 3 },
        { code: 'ME492', name: 'MEMS and Nanotechnology (Open Elec. III)', credits: 3 },
        { code: 'ME493', name: 'Microscale Transport Processes (Open Elec. III)', credits: 3 },
        { code: 'ME494', name: 'Pollution Control and Management (Open Elec. III)', credits: 3 },
        { code: 'ME495', name: 'Solar Architecture (Open Elec. III)', credits: 3 },
        { code: 'ME499', name: 'Project II', credits: 6 },
      ],
    }
  };

export const courseData: Record<string, any> = {};

for (const branch in rawCourseData) {
    courseData[branch] = {};
    for (const semester in rawCourseData[branch]) {
        courseData[branch][semester] = addDefaultResourceLinks(rawCourseData[branch][semester]);
    }
}
    
