export const nits = [
    { name: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar' },
    { name: 'Malaviya National Institute of Technology Jaipur' },
    { name: 'Maulana Azad National Institute of Technology Bhopal' },
    { name: 'Motilal Nehru National Institute of Technology Allahabad' },
    { name: 'National Institute of Technology Agartala' },
    { name: 'National Institute of Technology Arunachal Pradesh' },
    { name: 'National Institute of Technology Calicut' },
    { name: 'National Institute of Technology Delhi' },
    { name: 'National Institute of Technology Durgapur' },
    { name: 'National Institute of Technology Goa' },
    { name: 'National Institute of Technology Hamirpur' },
    { name: 'National Institute of Technology Karnataka, Surathkal' },
    { name: 'National Institute of Technology Meghalaya' },
    { name: 'National Institute of Technology Mizoram' },
    { name: 'National Institute of Technology, Nagaland' },
    { name: 'National Institute of Technology Patna' },
    { name: 'National Institute of Technology Puducherry' },
    { name: 'National Institute of Technology Raipur' },
    { name: 'National Institute of Technology Sikkim' },
    { name: 'National Institute of Technology, Silchar' },
    { name: 'National Institute of Technology, Srinagar' },
    { name: 'National Institute of Technology, Tiruchirappalli' },
    { name: 'National Institute of Technology, Uttarakhand' },
    { name: 'National Institute of Technology, Warangal' },
    { name: 'Sardar Vallabhbhai National Institute of Technology, Surat' },
    { name: 'Visvesvaraya National Institute of Technology, Nagpur' },
    { name: 'National Institute of Technology Andhra Pradesh' },
    { name: 'Indian Institute of Engineering Science and Technology, Shibpur' },
    { name: 'National Institute of Technology Manipur' },
    { name: 'National Institute of Technology, Rourkela' },
    { name: 'National Institute of Technology, Jamshedpur' },
    { name: 'National Institute of Technology, Kurukshetra' },
];
