export const nits = [
  "National Institute of Technology, Agartala",
  "Motilal Nehru National Institute of Technology, Allahabad",
  "National Institute of Technology, Arunachal Pradesh",
  "Maulana Azad National Institute of Technology, Bhopal",
  "National Institute of Technology, Calicut",
  "National Institute of Technology, Delhi",
  "National Institute of Technology, Durgapur",
  "National Institute of Technology, Goa",
  "National Institute of Technology, Hamirpur",
  "Malaviya National Institute of Technology, Jaipur",
  "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar",
  "National Institute of Technology, Jamshedpur",
  "National Institute of Technology, Kurukshetra",
  "National Institute of Technology, Manipur",
  "National Institute of Technology, Meghalaya",
  "National Institute of Technology, Mizoram",
  "National Institute of Technology, Nagaland",
  "Visvesvaraya National Institute of Technology, Nagpur",
  "National Institute of Technology, Patna",
  "National Institute of Technology, Puducherry",
  "National Institute of Technology, Raipur",
  "National Institute of Technology, Rourkela",
  "National Institute of Technology, Sikkim",
  "National Institute of Technology, Silchar",
  "National Institute of Technology, Srinagar",
  "Sardar Vallabhbhai National Institute of Technology, Surat",
  "National Institute of Technology, Surathkal",
  "National Institute of Technology, Tiruchirappalli",
  "National Institute of Technology, Uttarakhand",
  "National Institute of Technology, Warangal",
  "Sardar Vallabhbhai National Institute of Technology, Andhra Pradesh",
];
